name: xlo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  parse_server_sdk_flutter: ^3.1.0
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  get_it: ^7.2.0
  brasil_fields: ^1.3.0
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  dio: ^4.0.4
  shared_preferences: ^2.0.11
  path: ^1.8.0
  cached_network_image: ^3.2.0  
  intl: ^0.17.0
  carousel_slider: ^4.0.0
  readmore: ^2.1.0
  url_launcher: ^6.0.17
  toggle_switch: ^1.3.0
  connectivity: ^3.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.4
  build_runner: ^2.1.7

flutter:
  uses-material-design: true